#title: AVERtek # your name photo (or website title) here
logo1: "/images/avenidaPDlogo.png? raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <h1 style="text-align: center;" markdown="1"><b>UNIQUE PARTNERSHIP REFERRAL EVENT</h1></b>
  <br><br>
  <h2 style="text-align: center;" markdown="1"><b>Please RSVP by Wednesday, June 23rd, 2021</h2></b>
  <br><br>
  <h2 style="text-align: center;" markdown="1"><b>JOIN US:</b><a href="mailto:AvenidaPalmDesert@Sares-Regis.com?Subject=Professional Event RSVP" onclick="getOutboundLink('mailto:AvenidaPalmDesert@Sares-Regis.com'); return false;"<b> RSVP HERE</b></h2></a> 
  <br><br>
theme: jekyll-theme-minimal
# Google Analytics
google_analytics: UA-000000000-0 
