#title: AVERtek # your name photo (or website title) here
logo1: "/images/avenidaPDlogo.png? raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <h1 style="text-align: center;" markdown="1"><b>UNIQUE PARTNERSHIP REFERRAL EVENT</h1></b></a>
  <br><br>
  <h2 style="text-align: center;" markdown="1"><b>JOIN US:</b><a href="https://www.avenidapalmdesert.com/RSVP/" onclick="getOutboundLink('https://www.avenidapalmdesert.com/RSVP/'); return false;"<b> Sign Up Here</b></h2></a> 
  <br><br>
theme: jekyll-theme-minimal
# Google Analytics
google_analytics: UA-000000000-0 
