#title: AVERtek # your name photo (or website title) here
logo1: "/images/avenidaPDlogo.png? raw=true" # your photo (or logo) here
logo2: "/images/Upcoming Events.PNG? raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <h1 style="text-align: center;" markdown="1"><b>HEADER DESCRIPTION HERE</h1></b></a>
  <br><br>
  <h2 style="text-align: center;" markdown="1"><b>REGISTER HERE; CASH BONUS:</b><a href="https://alexanbahay.com/special/?utm_source=AVERtek&utm_medium=AR" onclick="getOutboundLink('https://alexanbahay.com/special/?utm_source=AVERtek&utm_medium=AR'); return false;"<b> USE CODE: DODGERS</b></h2></a> 
  <br><br>
theme: jekyll-theme-cayman
# Google Analytics
google_analytics: UA-000000000-0 
